### ISSUE TITLE
make package names lowercase

### ISSUE THREAD

**Issue by iwakeh** [tomlurge/converTor#1]
remove CamelCase from package names.

**Comment by rat10** [comment]
Thanks for the hint! Will do.

**Comment by rat10** [comment]
done :)

**Comment by iwakeh** [comment]
Package name is changed, thanks.
Just one more convention to follow: it might be useful to also change the source path names to lowercase, i.e., `src/converTor` to `src/convertor`.

**Comment by tomlurge** [comment]
did that too, thanks!

**Comment by iwakeh** [comment]
Thanks!
Is it committed to github? At least I couldn't see the change in the code overview: https://github.com/tomlurge/converTor/commit/ee2200f5fc7c556797ad869eb46c59599c3dc016

**Comment by tomlurge** [comment]
Aha. That's strange. I committed it 2 weeks ago. It is changed in my code, the IDE shows it correctly, the folder is named correctly but my Git-client does, like GitHub, still show the camelCased name. Right now I'm cluesless...

**Comment by tomlurge** [comment]
Okay, brute forced Git into recognizing the CaseChange.
