### ISSUE TITLE
project clean-up

### ISSUE THREAD

**Issue by iwakeh** [tomlurge/converTor#2]
I noticed the `attic` folder. Is it a 'leftover' from a former CVS repo?
Some code in there is described as not working or completely commented out.
I would suggest to remove this folder, if this is not used anymore. 

Same with some other notes and files. It is not clear which are the docs that one should read.
Just remove old stuff and trust `git` to remember everything :-)

**Comment by tomlurge** [comment]
Removed `attic` folder - grudgingly, because `git` is not always my friend :-/
Cleaned up the `docs` folder a little.
Documentation needs more love for sure, but that would be another issue.
