### ISSUE TITLE
explicit java version

### ISSUE THREAD

**Issue by iwakeh** [tomlurge/converTor#3]
The javac task doesn't explicitly state source and target version. Descriptor uses java 1.7; I didn't investigate the other dependencies.

Maybe add the `source="${source-and-target-java-version}"` and `target="${source-and-target-java-version}"` attributes to the ant task and set `source-and-target-java-version` to the version needed.

**Comment by tomlurge** [comment]
It works with Java 1.7 on my machine, so - without further investigating the other libraries - that should be fine. I changed build.xml as you suggested.

**Comment by iwakeh** [comment]
That's ok.

**Comment by tomlurge** [comment]
Thanks! Closing.
