### ISSUE TITLE
use constants for string literals

### ISSUE THREAD

**Issue by iwakeh** [tomlurge/converTor#5]
Those string literals that appear more than once are more convenient to maintain when using constants. 
For example the use of "json", but there are a few more:
`src/converTor/Writers.java:          case ("json") : writer = new WriterJson(type, date); break;`

`src/converTor/Args.java:  private String format = "json";`

`src/converTor/Args.java:      else if (formatArgument.equals("json")) {`

**Comment by tomlurge** [comment]
replaced string literals with calls for Booleans that had already been defined
