### ISSUE TITLE
ivestigate misterious IOE

### ISSUE THREAD

**Issue by iwakeh** [tomlurge/converTor#7]
This should be investigated to make sure that it really doesn't cause harm later:
in Types.java
`} catch (IOException e) {
      /* (Not sure why...) an IOException is always thrown for all schemata
         but the converter works nonetheless. */
    }`

**Comment by tomlurge** [comment]
Charmingly the IOE seems to be gone for good. Added proper logging in case it resurfaces.

**Comment by iwakeh** [comment]
That sound good.
Ready to be closed.

**Comment by tomlurge** [comment]
Thanks! Closing.
